### ISSUE TITLE
Need Help for flow Authentication

### ISSUE THREAD

**Issue by chondrosw** [cryptomator/cryptolib-swift#10]
Hello my name is Chondro, i need help to decrypt file. So my key as SHA256 String and need to decrypt file. how step do i do for using Cryptolib-swift? Because when i use it, authenticationFailure. Thank your so much

**Comment by tobihagemann** [comment]
Hi Chondro, without providing some context, I'm unable to give you any advice. Please go through the [README](https://github.com/cryptomator/cryptolib-swift#readme) more carefully, which describes on how to use this library in detail.

E.g., having a key as SHA256 string doesn't make much sense. Since this is an issue tracker (and I don't believe there is an issue with this library according to your description), please stick to the [forums](https://community.cryptomator.org/) if you have further questions.
