### ISSUE TITLE
High memory usage during encryption and decryption of large files

### ISSUE THREAD

**Issue by phil1995** [cryptomator/cryptolib-swift#8]
During the encryption and decryption of large files, there is an increased memory consumption.
This causes the process to terminate in applications that have a low memory limit (e.g. `FileProviderExtension`).

**Comment by StanoRiga** [comment]
Hi.
as stated here: https://community.cryptomator.org/t/issues-with-large-video-files-4-2gb-with-cryptomator-2-0-in-ios-15-0/8593/4?u=michael
the problem seems to persist with iOS Beta 2.0.0 (609) 
Logfile attached.
[org.cryptomator.ios.fileprovider 2021-11-19--20-34-32-482.log](https://github.com/cryptomator/cryptolib-swift/files/7574941/org.cryptomator.ios.fileprovider.2021-11-19--20-34-32-482.log)

**Comment by tobihagemann** [comment]
Thank you for reporting it! We'll still have to determine if this is actually an issue with cryptolib-swift or maybe this time with something else. After that, we should create a new issue and keep this closed.

**Comment by tobihagemann** [comment]
I think we're just dumb. We've fixed it in our libraries but we've never updated the dependency in our main app. 2.0.0 Beta 9 will definitely include the fix. :smile:
